### ISSUE TITLE
[issue] color, size에 따른 제품의 중복 저장 이슈

### ISSUE THREAD

**Issue by BY-ee** [BY-ee/project-closet#2]
### item 테이블
![image](https://github.com/user-attachments/assets/424ce335-8ff2-49c6-a0b5-f58b83707c01)

### item_detail 테이블
![image](https://github.com/user-attachments/assets/d11737a5-78ac-4a0a-a273-820b1a2ef35a)

<hr />

**item** 테이블과 **item_detail** 테이블 모두 *item_detail_id=8* 에 대한 중복 데이터가 존재
- 두 테이블 중 어느 테이블을 조회하더라도 중복 데이터를 제거하는 로직 필요
- **item** 테이블: `색상`, `사이즈`가 종속되어 있어 테이블의 중복 데이터 제거 불가
 **item_detail** 테이블: `색상별 이미지`가 종속되어 있어 마찬가지로 테이블의 중복 데이터 제거 불가

상품 데이터를 사용하는 로직을 작성할 시 테이블의 중복 데이터를 신경써야 함

따라서,

1. 현황 유지 (db에 저장되는 데이터를 유지, 중복 데이터는 서버단, 클라이언트단에서 제거)
2. 테이블 수정 (**item** 테이블의 `color`, `size` 컬럼을 **item_detail**로 이동, **item** 테이블 최소화)
3. ~~새로운 테이블 생성~~

**Comment by NAMEJM-sys** [comment]
### 수정된 item_detail 테이블

![image](https://github.com/user-attachments/assets/bc5bfb89-1fa4-4080-9015-f10012d31f21)

------

### 데이터베이스 설계 개선 
- 기존 문제점
  - item_detail_id의 중복된 데이터가 item_detail 테이블에도 여럿 존재하여 데이터 정규화가 지켜지지 않음
  - jpa 기본 문법으로 item의 데이터를 별도의 List 형태로 가져오기 어려움
  



- 개선 방식
  - item_detail 테이블에서 중복 데이터를 제거, 고유한 데이터로 유지 (예, item_detail.id = 8)
  - 어플리케이션 레벨의 개선을 통해 동 문제 해결

 

<br> 

### 어플리케이션 레벨의 개선 
- 기존 문제점
  - 중복된 데이터를 제거하지 않을 경우,  Main Page에서 필요 이상의 데이터를 가져오게 됨


- 개선 방식
  - DTO 활용 `ItemDetailItemDTO`
  - JPQL 최적화 데이터 조희
  - Entity Join시 List 구조 사용을 위한 `@OneToMany` ↔ `@ManyToOne` 사용 
  - 사용에 필요한 최적의 데이터만 호출
 

<br> 

### 프론트엔드 레벨의 개선 
- 기존 문제점
  - 중복 데이터 처리를 하지 못하여 필요 이상의 전체 데이터를 받아 필터를 하는 불필요한 개발 작업 추가
  - 출력되는 결과에 비해 네트워크 트래픽이 필요 이상으로 발생

- 개선 방식
  - 중복 데이터 처리로 인해 필요한 데이터를 받아 개발 작업 최소화
  - 네트워크 트래픽 감소로 인한 UX 향상

<br> 

### 리팩토링 결과
- 데이터 정규화 방식에 부합하지 않던 DB 설계를 정상화
- 어플리케이션 레벨 개선에 따른 전체적인 리팩토링 및 UX 향상

<br> 

------

### 실제 코드들

<br> 

... domain/item.java 중

```

@ManyToOne
@JoinColumn(name = "item_detail_id")
private ItemDetail itemDetail;
```
<br> 
... domain/itemDetail.java 중

```

@OneToMany(mappedBy = "itemDetail")
private List<Item> items;
``` 

<br> 
... repository/ItemDetialRepository.java 중

```
    @Query("SELECT new com.project.dto.ItemDetailItemDTO(i.id, i.item_count, i.color, i.size, i.status, i.created_at, " +
            "d.id, d.item_price, d.views, d.item_name, d.item_category, d.main_image, d.detail_image, d.status, d.created_at) " +
            "FROM Item i JOIN i.itemDetail d WHERE d.id = :itemDetailId")
    List<ItemDetailItemDTO> findItemDetailWithItem(@Param("itemDetailId") Long itemDetailId);
```
